CREATE TABLE auction_auction_player
(
    auction_player_id BIGINT NOT NULL,
    auction_id        BIGINT NOT NULL
);

CREATE TABLE auction_players
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    player_id     BIGINT,
    base_price_id BIGINT,
    CONSTRAINT pk_auction_players PRIMARY KEY (id)
);

CREATE TABLE auctions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    venue      VARCHAR(255),
    status     SMALLINT,
    event_date date,
    title      VARCHAR(255),
    CONSTRAINT pk_auctions PRIMARY KEY (id)
);

CREATE TABLE base_price
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    player_id     BIGINT,
    tournament_id BIGINT,
    base_price    DECIMAL,
    CONSTRAINT pk_base_price PRIMARY KEY (id)
);

CREATE TABLE bids
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    is_sold           BOOLEAN                                 NOT NULL,
    current_price     DECIMAL,
    auction_player_id BIGINT,
    auction_id        BIGINT,
    franchise_id      BIGINT,
    CONSTRAINT pk_bids PRIMARY KEY (id)
);

CREATE TABLE franchiese
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    city       VARCHAR(255),
    country    VARCHAR(255),
    phone      VARCHAR(255),
    email      VARCHAR(255),
    address    VARCHAR(255),
    CONSTRAINT pk_franchiese PRIMARY KEY (id)
);

CREATE TABLE franchise_tournament
(
    franchise_id  BIGINT NOT NULL,
    tournament_id BIGINT NOT NULL
);

CREATE TABLE player_skill
(
    player_id BIGINT NOT NULL,
    skill_id  BIGINT NOT NULL
);

CREATE TABLE player_team
(
    player_id BIGINT NOT NULL,
    team_id   BIGINT NOT NULL
);

CREATE TABLE player_tournament
(
    player_id     BIGINT NOT NULL,
    tournament_id BIGINT NOT NULL
);

CREATE TABLE players
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    dob        date,
    country    VARCHAR(255),
    CONSTRAINT pk_players PRIMARY KEY (id)
);

CREATE TABLE skills
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    rating          INTEGER,
    years_of_exp    INTEGER,
    expertise_level VARCHAR(255),
    CONSTRAINT pk_skills PRIMARY KEY (id)
);

CREATE TABLE tournaments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255),
    location      VARCHAR(255),
    start_date    date,
    end_date      date,
    alloted_purse DECIMAL,
    CONSTRAINT pk_tournaments PRIMARY KEY (id)
);

CREATE TABLE tournaments_players
(
    tournament_id BIGINT NOT NULL,
    players_id    BIGINT NOT NULL
);

ALTER TABLE auction_players
    ADD CONSTRAINT FK_AUCTION_PLAYERS_ON_BASEPRICE FOREIGN KEY (base_price_id) REFERENCES base_price (id);

ALTER TABLE auction_players
    ADD CONSTRAINT FK_AUCTION_PLAYERS_ON_PLAYER FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE base_price
    ADD CONSTRAINT FK_BASE_PRICE_ON_PLAYER FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE base_price
    ADD CONSTRAINT FK_BASE_PRICE_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE bids
    ADD CONSTRAINT FK_BIDS_ON_AUCTION FOREIGN KEY (auction_id) REFERENCES auctions (id);

ALTER TABLE bids
    ADD CONSTRAINT FK_BIDS_ON_AUCTIONPLAYER FOREIGN KEY (auction_player_id) REFERENCES auction_players (id);

ALTER TABLE bids
    ADD CONSTRAINT FK_BIDS_ON_FRANCHISE FOREIGN KEY (franchise_id) REFERENCES franchiese (id);

ALTER TABLE auction_auction_player
    ADD CONSTRAINT fk_aucaucpla_on_auction FOREIGN KEY (auction_id) REFERENCES auctions (id);

ALTER TABLE auction_auction_player
    ADD CONSTRAINT fk_aucaucpla_on_auction_player FOREIGN KEY (auction_player_id) REFERENCES auction_players (id);

ALTER TABLE franchise_tournament
    ADD CONSTRAINT fk_fratou_on_franchise FOREIGN KEY (franchise_id) REFERENCES franchiese (id);

ALTER TABLE franchise_tournament
    ADD CONSTRAINT fk_fratou_on_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE player_skill
    ADD CONSTRAINT fk_plaski_on_player FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE player_skill
    ADD CONSTRAINT fk_plaski_on_skill FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE player_team
    ADD CONSTRAINT fk_platea_on_player FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE player_team
    ADD CONSTRAINT fk_platea_on_team FOREIGN KEY (team_id) REFERENCES franchiese (id);

ALTER TABLE player_tournament
    ADD CONSTRAINT fk_platou_on_player FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE player_tournament
    ADD CONSTRAINT fk_platou_on_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE tournaments_players
    ADD CONSTRAINT fk_toupla_on_player FOREIGN KEY (players_id) REFERENCES players (id);

ALTER TABLE tournaments_players
    ADD CONSTRAINT fk_toupla_on_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments (id);