ALTER TABLE auction_auction_player
    DROP CONSTRAINT fk_aucaucpla_on_auction;

ALTER TABLE auction_auction_player
    DROP CONSTRAINT fk_aucaucpla_on_auction_player;

ALTER TABLE bids
    DROP CONSTRAINT fk_bids_on_auction;

ALTER TABLE bids
    DROP CONSTRAINT fk_bids_on_franchise;

ALTER TABLE franchise_tournament
    DROP CONSTRAINT fk_fratou_on_franchise;

ALTER TABLE player_team
    DROP CONSTRAINT fk_platea_on_team;

ALTER TABLE tournaments_players
    DROP CONSTRAINT fk_toupla_on_player;

ALTER TABLE tournaments_players
    DROP CONSTRAINT fk_toupla_on_tournament;

CREATE TABLE franchises
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    city       VARCHAR(255),
    country    VARCHAR(255),
    phone      VARCHAR(255),
    email      VARCHAR(255),
    address    VARCHAR(255),
    CONSTRAINT pk_franchises PRIMARY KEY (id)
);

CREATE TABLE stats
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    player_id      BIGINT,
    cricket_format VARCHAR(255)                            NOT NULL,
    matches_played INTEGER,
    highest_level  VARCHAR(255),
    runs_scored    INTEGER,
    balls_played   INTEGER,
    wickets_taken  INTEGER,
    balls_bowled   INTEGER,
    runs_conceded  INTEGER,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);

CREATE TABLE teams
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(255),
    min_players     INTEGER,
    max_players     INTEGER,
    remaining_purse DECIMAL,
    franchise_id    BIGINT,
    tournament_id   BIGINT,
    phone           VARCHAR(255),
    email           VARCHAR(255),
    address         VARCHAR(255),
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

ALTER TABLE players
    ADD address VARCHAR(255);

ALTER TABLE players
    ADD email VARCHAR(255);

ALTER TABLE players
    ADD phone VARCHAR(255);

ALTER TABLE auction_players
    ADD auction_id BIGINT;

ALTER TABLE skills
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE skills
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE skills
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE auctions
    ADD tournament_id BIGINT;

ALTER TABLE auction_players
    ADD CONSTRAINT uc_auction_players_base_price UNIQUE (base_price_id);

ALTER TABLE auctions
    ADD CONSTRAINT uc_auctions_tournament UNIQUE (tournament_id);

ALTER TABLE auctions
    ADD CONSTRAINT FK_AUCTIONS_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE auction_players
    ADD CONSTRAINT FK_AUCTION_PLAYERS_ON_AUCTION FOREIGN KEY (auction_id) REFERENCES auctions (id);

ALTER TABLE bids
    ADD CONSTRAINT FK_BIDS_ON_FRANCHISE FOREIGN KEY (franchise_id) REFERENCES franchises (id);

ALTER TABLE stats
    ADD CONSTRAINT FK_STATS_ON_PLAYER FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE teams
    ADD CONSTRAINT FK_TEAMS_ON_FRANCHISE FOREIGN KEY (franchise_id) REFERENCES franchises (id);

ALTER TABLE teams
    ADD CONSTRAINT FK_TEAMS_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournaments (id);

ALTER TABLE franchise_tournament
    ADD CONSTRAINT fk_fratou_on_franchise FOREIGN KEY (franchise_id) REFERENCES franchises (id);

ALTER TABLE player_team
    ADD CONSTRAINT fk_platea_on_team FOREIGN KEY (team_id) REFERENCES teams (id);

DROP TABLE auction_auction_player CASCADE;

DROP TABLE franchiese CASCADE;

DROP TABLE tournaments_players CASCADE;

ALTER TABLE bids
    DROP COLUMN auction_id;

ALTER TABLE players
    ALTER COLUMN first_name SET NOT NULL;