# Server (Prod)
server.port=8082
server.servlet.context-path=/api
# Database (production)
spring.datasource.url=${DB_PROD_URL}
spring.datasource.username=${DB_PROD_USERNAME}
spring.datasource.password=${DB_PROD_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# Logging (minimal)
logging.level.root=WARN

