# Server (Test)
server.port=8082

# Database (staging server)
spring.datasource.url=${DB_TEST_URL}
spring.datasource.username=${DB_TEST_USERNAME}
spring.datasource.password=${DB_TEST_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logging
logging.level.root=INFO