#App info
spring.application.name=backend
server.servlet.context-path=/api
# Server (Dev)
server.port=8081
# Database (Local)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Logging (more verbose)
#logging.level.org.springframework=DEBUG
# Swagger
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/swagger
springdoc.override-with-generic-response=false
